### ISSUE TITLE
Frontmatter is missing when adding a new post

### ISSUE THREAD

**Issue by dabonnestor** [LokeCarlsson/gridsome-starter-bootstrap#6]
Hi. When adding a new blog post on forestry the front matter wasn't added on the markdown file. This is what I'm trying to add a new post.

![apple-ipsum](https://user-images.githubusercontent.com/22286294/57970211-3eb91500-79b1-11e9-9206-5c1fab5bc21d.JPG)

**Comment by LokeCarlsson** [comment]
I took a look at this issue and I'm experiencing the same issue on multiple of my sites. My initial thoughts are that this issue is on Forestry and nothing I can do at the moment. I have contacted the developers at Forestry and will keep you updated on any findings i make. Thank you for reporting this!

**Comment by LokeCarlsson** [comment]
@dabonnestor The Forestry team is working on a solution for this now!

**Comment by dabonnestor** [comment]
@LokeCarlsson Thanks for the update. As this is likely an issue from forestry, I will now close this issue.

**Comment by LokeCarlsson** [comment]
Yep, their dev team released a fix earlier today, confirmed that it is working now! Cheers for reporting and good luck with your project.
